###
# Essentials
###

# Keybind to reload this configs
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded tmux config!"

# Turn on mouse to scroll to terminal and clickable status line
set -g mouse on

# Use 24 bit colors (make sure terminal supports it)
set-option -sa terminal-overrides ",xterm*:Tc"

# Start windows, and panes at 1 instead of 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on


###
# Styling
###

# Colors
BG="#282C34",
LBG="#3F4451",
FG="#cdd6f4",
LFG="#abb2bf",
YELLOW="#e5c07b",
CYAN="#56b6c2",
GREEN="#98c379",
MAGENTA="#c678dd",
VIOLET="#cba6f7",
BLUE="#61afef",
RED="#e06c75",

# Nerd Font Characters
HALF_ROUND_OPEN=""
HALF_ROUND_CLOSE=""

# Get window icon bash script path
GET_WINDOW_ICON_SCRIPT_PATH=~/.config/tmux/scripts/get-window-icon.sh

# Move status line to top/bottom
set-option -g status-position bottom

# Set colors for statusline
set-option -g status-style bg=${BG},fg=${LFG}

# Set justification
set-option -g status-justify left

# Adjust max length of statusline to prevent getting cut off
set-option -g status-left-length 25
set-option -g status-right-length 25

# Set contents of left statusline
set-option -g status-left "\
#[bg=${BG},fg=${LBG}]${HALF_ROUND_OPEN}\
#[bg=${LBG},fg=${LFG}, bold] #{session_name} \
#[bg=${BG},fg=${LBG}]${HALF_ROUND_CLOSE}\
   "

# Set contents of right statusline
set-option -g status-right "  \
#[bg=${BG},fg=${LBG}]${HALF_ROUND_OPEN}\
#[bg=${LBG},fg=${LFG}, bold] #{host} \
#[bg=${BG},fg=${LBG}]${HALF_ROUND_CLOSE}\
"

# Style inactive windows
set-option -g window-status-format "\
#[bg=${BG},fg=${BG}]${HALF_ROUND_OPEN}\
 \
#[bg=default, fg=default]#(${GET_WINDOW_ICON_SCRIPT_PATH} '#{window_name}')\
 \
#{window_name}\
 \
#[bg=${BG},fg=${BG}]${HALF_ROUND_CLOSE}\
"

# Style active window
set-option -g window-status-current-format "\
#[bg=${BG},fg=${MAGENTA}]${HALF_ROUND_OPEN}\
#[bg=${MAGENTA}, fg=${BG}, bold] #(${GET_WINDOW_ICON_SCRIPT_PATH} '#{window_name}')\
 \
#{window_name}\
 \
#[bg=${BG},fg=${MAGENTA}]${HALF_ROUND_CLOSE}\
"

# Adjust space between windows
set-option -g window-status-separator ""


###
# Vim
###

# Allow use of vim keybinds when using copy mode
set-window-option -g mode-keys vi

# Keybinds for copy mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel


###
# Navigations
###

# Open panes and windows in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"


###
# Persistence
###

# Auto restore when first client attaches
set -g @resurrect-strategy-nvim 'session'
set -g @continuum-restore 'on'
# set -g status-right 'Continuum status: #{continuum_status}'
# set -g @continuum-save-interval '15'


###
# Plugins
###

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
