# Disable random quote/text over the wallpaper
splash = false

# Set the same wallpaper to all monitors
wallpaper {
    monitor = 
    path = ~/Pictures/assets/wallpapers/whispers-of-the-eastern-sea.png
}

